"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# --- MONGO DB PRIMARY KEY PATCH ---
# This forces built-in Django apps (auth, admin, sessions, etc.) to use 
# MongoDB-compatible ObjectIds for their primary keys.
import django.apps
from django.apps import AppConfig

# Store original __init__ to avoid recursion if needed, though here we replace the class-level attribute
original_appconfig_init = AppConfig.__init__

# Patching AppConfig globally BEFORE apps are loaded
# This ensures every app, including built-in ones, defaults to ObjectIdAutoField
AppConfig.default_auto_field = 'django_mongodb_backend.fields.ObjectIdAutoField'

# Targeted patching for core Django apps that might have already been initialized or have specific needs
def patch_core_configs():
    import django.contrib.auth.apps
    import django.contrib.admin.apps
    import django.contrib.contenttypes.apps
    import django.contrib.sessions.apps
    
    configs = [
        django.contrib.auth.apps.AuthConfig,
        django.contrib.admin.apps.AdminConfig,
        django.contrib.contenttypes.apps.ContentTypesConfig,
        django.contrib.sessions.apps.SessionsConfig,
    ]
    for config in configs:
        config.default_auto_field = 'django_mongodb_backend.fields.ObjectIdAutoField'

patch_core_configs()

DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'
# --- END PATCH ---

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-un&0!z6))nq+bwr-%i1253o2@h-rwwm5ry_1-bz!l#fnj_9)_^'

# --- MONGO DB PRIMARY KEY PATCH ---
# This must run BEFORE any models are loaded.
# It ensures built-in apps like 'auth' and 'admin' use MongoDB ObjectIds.
import django_mongodb_backend.fields
from django.apps import AppConfig
AppConfig.default_auto_field = 'django_mongodb_backend.fields.ObjectIdAutoField'
# --- END PATCH ---

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_mongodb_backend',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases





# 1. Standard global default
# (Already set at top)

# 2. Specific overrides for built-in Django apps
# This forces the internal apps to use MongoDB-compatible IDs
SILENCED_SYSTEM_CHECKS = ["mongodb.E001"]


DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': 'algorianAI',
        'HOST': '127.0.0.1',
        'PORT': 27017,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CORS_ALLOW_ALL_ORIGINS = True

